version: '3.8'

services:
  reversi-model:
    build:
      context: .
      dockerfile: Dockerfile
    image: reversi-model:latest
    container_name: reversi-model
    volumes:
      - ./:/app
      # 訓練データの永続化
      - ./output:/app/output
      - ./logs:/app/logs
    ports:
      - "6006:6006"  # TensorBoard用
    # GPU設定
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    # デフォルトでは単なるシェルを起動
    command: bash
    # dev環境では長時間稼働させる
    tty: true
    stdin_open: true
    # 推奨：TensorFlowのCUDAログレベル設定
    environment:
      - TF_CPP_MIN_LOG_LEVEL=1  # INFO + Warning のみ表示
