services:
  app:
    build: .
    container_name: reversi-model
    volumes:
      - ./:/app
      - ./output:/app/output
      - ./logs:/app/logs
    ports:
      - "6006:6006"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    tty: true
    stdin_open: true
    environment:
      - TF_CPP_MIN_LOG_LEVEL=1
